# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BaoKanIOS' do
    pod 'RxSwift',    '~> 2.0.0-rc'
    pod 'RxCocoa',    '~> 2.0.0-rc'
    pod 'RxBlocking', '~> 2.0.0-rc'
    pod 'SnapKit'
    pod 'YYWebImage'
    pod 'SVProgressHUD'
    pod 'SDCycleScrollView','~> 1.3'
    pod 'Alamofire'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'MJRefresh'
end

target 'BaoKanIOSTests' do
    
end

target 'BaoKanIOSUITests' do
    
end

