# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BaoKanIOS' do
    pod 'SnapKit', '~> 0.21.0'
    pod 'YYWebImage', '~> 1.0.3'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDCycleScrollView','~> 1.3'
    pod 'Alamofire', '~> 3.4.0'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'pop', '~> 1.0.9'
    pod 'IQKeyboardManagerSwift'
end

target 'BaoKanIOSTests' do
    
end

target 'BaoKanIOSUITests' do
    
end

